# Generated by Django 4.1 on 2022-08-12 18:53

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("initial_file", "0001_initial"),
        ("conversion_file", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Convert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Unique identification",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now=True, verbose_name="Date of creation"),
                ),
                (
                    "date_published",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Publishingdate",
                    ),
                ),
                (
                    "date_expired",
                    models.DateTimeField(blank=True, null=True, verbose_name="Expiring date"),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date of last update"),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(blank=True, null=True, verbose_name="Delete date"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in review", "In review"),
                            ("published", "Published"),
                            ("changes requested", "Changes requested"),
                            ("schedule", "Schedule"),
                        ],
                        default="draft",
                        max_length=255,
                    ),
                ),
                (
                    "from_action",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "to_action",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("pending", "Pending"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=255,
                    ),
                ),
                (
                    "conversion_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conversion_file.conversionfile",
                    ),
                ),
                (
                    "initial_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="initial_file.initialfile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
