# Generated by Django 4.1 on 2022-10-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversion_file", "0001_initial"),
        ("convert", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="convert",
            name="conversion_file",
        ),
        migrations.AddField(
            model_name="convert",
            name="conversion_files",
            field=models.ManyToManyField(blank=True, to="conversion_file.conversionfile"),
        ),
    ]
