# Generated by Django 4.1.3 on 2022-11-27 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converted_files", "0001_initial"),
        ("conversions", "0002_conversion_initial_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversion",
            name="converted_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="converted_files.convertedfile",
            ),
        ),
    ]
