# Generated by Django 4.1.3 on 2022-11-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.RemoveField(
            model_name="page",
            name="date_expired",
        ),
        migrations.RemoveField(
            model_name="page",
            name="date_published",
        ),
        migrations.AddField(
            model_name="page",
            name="markup_data",
            field=models.TextField(blank=True, null=True, verbose_name="Structured markup data"),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_description",
            field=models.TextField(blank=True, null=True, verbose_name="Meta description"),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_image",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Meta image"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_keywords",
            field=models.TextField(
                blank=True, max_length=255, null=True, verbose_name="Meta keywords"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_title",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=55,
                null=True,
                verbose_name="Meta title",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date of creation"),
        ),
        migrations.AlterField(
            model_name="page",
            name="state",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=255,
            ),
        ),
    ]
