# Generated by Django 4.1.3 on 2022-11-22 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config_file", "0001_initial"),
        ("action", "0003_action_config_file_alter_action_compressions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="config_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="config_file.configfile",
            ),
        ),
    ]
